import esbuild from 'esbuild';
import process from 'process';
import builtins from 'builtin-modules';
import { copyFileSync, existsSync, mkdirSync, cpSync, rmSync } from 'fs';

const banner = `/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/
`;

const prod = process.argv[2] === 'production';
const RELEASE_PLUGIN_DIR = 'release/TikzJaxObsidian';

const mainBuildOptions = {
	banner: { js: banner },
	entryPoints: ['src/main.ts'],
	bundle: true,
	external: [
		'obsidian',
		'electron',
		'@codemirror/autocomplete',
		'@codemirror/collab',
		'@codemirror/commands',
		'@codemirror/language',
		'@codemirror/lint',
		'@codemirror/search',
		'@codemirror/state',
		'@codemirror/view',
		'@lezer/common',
		'@lezer/highlight',
		'@lezer/lr',
		...builtins
	],
	format: 'cjs',
	target: 'es2018',
	logLevel: 'info',
	sourcemap: prod ? false : 'inline',
	treeShaking: true,
	outfile: 'main.js',
	minify: prod,
	define: {
		global: 'window'
	}
};

const workerBuildOptions = {
	banner: { js: banner },
	entryPoints: ['src/tex-worker.ts'],
	bundle: true,
	format: 'iife',
	platform: 'browser',
	target: 'es2018',
	logLevel: 'info',
	sourcemap: prod ? false : 'inline',
	treeShaking: true,
	outfile: 'tex-worker.js',
	minify: prod,
	define: {
		global: 'globalThis'
	}
};

async function copyArtifacts() {
	if (!existsSync('dist')) {
		mkdirSync('dist', { recursive: true });
	}

	rmSync(RELEASE_PLUGIN_DIR, { recursive: true, force: true });
	mkdirSync(RELEASE_PLUGIN_DIR, { recursive: true });

	if (existsSync('main.js')) {
		copyFileSync('main.js', 'dist/main.js');
		copyFileSync('main.js', `${RELEASE_PLUGIN_DIR}/main.js`);
	}
	if (existsSync('tex-worker.js')) {
		copyFileSync('tex-worker.js', 'dist/tex-worker.js');
		copyFileSync('tex-worker.js', `${RELEASE_PLUGIN_DIR}/tex-worker.js`);
	}
	if (existsSync('manifest.json')) {
		copyFileSync('manifest.json', 'dist/manifest.json');
		copyFileSync('manifest.json', `${RELEASE_PLUGIN_DIR}/manifest.json`);
	}
	if (existsSync('styles.css')) {
		copyFileSync('styles.css', 'dist/styles.css');
		copyFileSync('styles.css', `${RELEASE_PLUGIN_DIR}/styles.css`);
	}
	if (existsSync('resources')) {
		cpSync('resources', 'dist/resources', { recursive: true });
		cpSync('resources', `${RELEASE_PLUGIN_DIR}/resources`, { recursive: true });
	}
}

if (prod) {
	await esbuild.build(mainBuildOptions);
	await esbuild.build(workerBuildOptions);
	await copyArtifacts();
	console.log('✅ Production build complete');
} else {
	const mainCtx = await esbuild.context(mainBuildOptions);
	const workerCtx = await esbuild.context(workerBuildOptions);
	await mainCtx.watch();
	await workerCtx.watch();
	await copyArtifacts();
	console.log('👀 Watching for changes...');
}
